### ISSUE TITLE
Metadata Update

### ISSUE THREAD

**Issue by reeshmabijosh** [Benzhaomin/covid-ddpb#1]
Hello,
Your dataset was added to CoronaWhy (https://www.coronawhy.org/) Data Lake on Dataverse as a piece of common COVID-19 data frame http://datasets.coronawhy.org/dataset.xhtml?persistentId=doi:10.5072/FK2/RNGBW9
Would you be willing to help with the maintenance of your dataset in Dataverse, e.g. adding the relevant metadata and keeping the dataset up-to-date? That will help to make the dataset findable and accessible for the medical science community.

**Comment by Benzhaomin** [comment]
Sure, give me permissions on the dataset and I'll take care of it. Same username: benzhaomin

**Comment by k-goncharova** [comment]
Thanks for your willingness to contribute, Benjamin. I've just given you the permissions.
